site_name: Projeto Compiladores - Grupo 11
repo_name: "compiladores-g11"
repo_url: "https://github.com/arthurfernandesj/Compiladores"

theme:
  name: material
  language: "pt-BR"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Modo Claro

nav:
  - Home: index.md

  - Sobre:
      - Escopo: sobre/escopo.md
      - Objetivos: sobre/objetivos.md

  - Arquitetura:
      - Visão Geral: arquitetura/visao-geral.md
      - Léxico: arquitetura/lexico.md
      - Sintático: arquitetura/sintatico.md
      - Semântico: arquitetura/semantico.md
      - Código: arquitetura/codigo.md

  - Planejamento:
      - Backlog: planejamento/backlog.md
      - Sprints: planejamento/sprints.md

  - Evolução:
      - Ponto de Controle 1: evolucao/p1.md
      - Ponto de Controle 2: evolucao/p2.md

  - Testes:
      - Testes: testes/index.md
  - Documentação:
      - Estrutura: documentacao/estrutura.md
      - Execução: documentacao/execucao.md
      
  - Demo:
      - Demo: demo/demo.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true